### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by cool0nik** [painhardcore/emc-testtask#1]
localhost:/go/src/github.com/painhardcore/emc-testtask # docker build -f ./Dockerfile .
Sending build context to Docker daemon   16.3MB
Step 1/9 : FROM golang:alpine as builder
 ---> 34d3217973fd
Step 2/9 : RUN mkdir /build
 ---> Using cache
 ---> 7f4a8f0eeeeb
Step 3/9 : ADD . /go/src/github.com/painhardcore/emc-testtask/
 ---> Using cache
 ---> 51cb858f2728
Step 4/9 : WORKDIR /go/src/github.com/painhardcore/emc-testtask/
 ---> Using cache
 ---> a7381a0067ed
Step 5/9 : RUN CGO_ENABLED=0 GOOS=linux go build -o main .
 ---> Running in 98ed057452f2
handlers.go:7:2: cannot find package "github.com/labstack/echo" in any of:
        /usr/local/go/src/github.com/labstack/echo (from $GOROOT)
        /go/src/github.com/labstack/echo (from $GOPATH)
main.go:7:2: cannot find package "github.com/labstack/echo/middleware" in any of:
        /usr/local/go/src/github.com/labstack/echo/middleware (from $GOROOT)
        /go/src/github.com/labstack/echo/middleware (from $GOPATH)
handlers.go:8:2: cannot find package "github.com/tarantool/go-tarantool" in any of:
        /usr/local/go/src/github.com/tarantool/go-tarantool (from $GOROOT)
        /go/src/github.com/tarantool/go-tarantool (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -o main .' returned a non-zero code: 1

**Comment by painhardcore** [comment]
@cool0nik Thanks for opening this issue ,It's fixed in #7.
This Dockerfile is building even without vendor folder.
And probably you want to build app with all dependencies :

```
docker-compose up
```
