### ISSUE TITLE
What happens if serialNumber is zero

### ISSUE THREAD

**Issue by edkovm** [painhardcore/emc-testtask#2]
https://github.com/painhardcore/emc-testtask/blob/64c47c87ea317ce0071c9b2aefbd02aa785b5efd/handlers.go#L15

Probably we need to ensure that input serialNumber is not zero.
Something like:
        // S/N is zero
	if s == 0 {
		return c.NoContent(http.StatusNoContent)
	}

**Comment by painhardcore** [comment]
@edkovm , thanks for opening this issue , of course we need to implement zero serialNumber scenario.
Like you proposed , this issue is fixed in https://github.com/painhardcore/emc-testtask/pull/3
