### ISSUE TITLE
H/A and Scalability

### ISSUE THREAD

**Issue by gusakk** [painhardcore/emc-testtask#5]
Please describe H/A and scalability purposes more detail (external load balancer, scalability of storage, service discovery). You can attach the picture if it is useful.

Also what will you do in this application to guarantee that the data has been written to the specified storage successfully?

**Comment by painhardcore** [comment]
If we are talking about http server, json as data format and tarantool as database...
It depends how many requests needs to handle.
At first we can do it with :
- HA proxy as loadbalancer for external requests.
- Consul for service discovery

For storage we're using Tarantool and it already has everything we want for scaling - master-slave, master-master replication and sharding. And has ACID transactions guarantee that the data has been written to the storage successfully.

**Comment by gusakk** [comment]
Thanks
